name: 'My Composite Action'
description: 'Runs multiple steps as a single action'
inputs:
  example-input:
    description: 'An example input'
    required: true
    default: 'default-value'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a script
      run: echo "Hello, ${{ inputs.example-input }}!"
      shell: bash
