name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

permissions:
  contents: read

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello, manually triggered"
          echo "token is ${{ github.token }}"

      - name: Run My Composite Action
        uses: ./.github/actions/myaction
        with:
          example-input: "World"
