name: Simple Workflow

on:
  pull_request:
    
    
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, pull  requested"
        


